# Generated by Django 5.2.16 on 2026-07-28 11:13

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('female', 'Féminin'), ('male', 'Masculin'), ('mixed', 'Mixte')], db_index=True, max_length=10)),
                ('origin', models.CharField(blank=True, max_length=150)),
                ('meaning', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'prénom',
                'verbose_name_plural': 'prénoms',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_first_name_case_insensitive')],
            },
        ),
    ]
