# Generated by Django 5.2.16 on 2026-07-28 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Terminée'), ('archived', 'Archivée')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_searches', to='api.profile')),
            ],
            options={
                'verbose_name': 'recherche de prénoms',
                'verbose_name_plural': 'recherches de prénoms',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['creator', 'status'], name='search_creator_status_idx')],
            },
        ),
    ]
