# Generated by Django 5.2.16 on 2026-07-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_namesearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameSearchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('member', 'Participant')], default='member', max_length=10)),
                ('invitation_status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_participations', to='api.profile')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.namesearch')),
            ],
            options={
                'verbose_name': 'participant à une recherche',
                'verbose_name_plural': 'participants aux recherches',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['profile', 'invitation_status'], name='participant_invite_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('search', 'profile'), name='unique_search_participant')],
            },
        ),
    ]
