# Generated by Django 5.2.16 on 2026-07-28 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_namesearchparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('liked', 'Aimé'), ('rejected', 'Refusé')], db_index=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='api.firstname')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='api.namesearchparticipant')),
            ],
            options={
                'verbose_name': 'décision sur un prénom',
                'verbose_name_plural': 'décisions sur les prénoms',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['participant', 'choice'], name='decision_part_choice_idx')],
                'constraints': [models.UniqueConstraint(fields=('participant', 'first_name'), name='unique_participant_first_name')],
            },
        ),
    ]
