# Generated by Django 5.2.16 on 2026-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_namesearch_genders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedecision',
            name='choice',
            field=models.CharField(choices=[('liked', 'Aimé'), ('rejected', 'Refusé'), ('skipped', 'Passé')], db_index=True, max_length=8),
        ),
    ]
