from django.urls import path

from .views import (
    AdminView,
    CourseUnitDetailView,
    CourseUnitListCreateView,
    HealthView,
    LearningObjectiveDetailView,
    LearningObjectiveListCreateView,
    LearnerTrainingListView,
    MeView,
    PublicRawMaterialFileView,
    PublicTrainingDetailView,
    PublicTrainingListView,
    RawMaterialDetailView,
    RawMaterialDownloadView,
    RawMaterialListCreateView,
    RawMaterialPreviewTokenView,
    RawMaterialPreviewView,
    TrainingDetailView,
    TrainingEnrichmentGenerateView,
    TrainingStructureGenerateView,
    TrainingStructurePublishView,
    TrainingListCreateView,
    UserListView,
    UserRoleView,
    UserTrainingAssignmentView,
)


urlpatterns = [
    path("health/", HealthView.as_view(), name="health"),
    path(
        "public/v1/trainings/",
        PublicTrainingListView.as_view(),
        name="public-training-list",
    ),
    path(
        "public/v1/trainings/<int:training_id>/",
        PublicTrainingDetailView.as_view(),
        name="public-training-detail",
    ),
    path(
        "public/v1/trainings/<int:training_id>/raw-materials/"
        "<int:material_id>/file/",
        PublicRawMaterialFileView.as_view(),
        name="public-raw-material-file",
    ),
    path("me/", MeView.as_view(), name="me"),
    path("admin/", AdminView.as_view(), name="admin"),
    path("admin/users/", UserListView.as_view(), name="user-list"),
    path(
        "admin/users/<int:profile_id>/trainings/",
        UserTrainingAssignmentView.as_view(),
        name="user-training-assignments",
    ),
    path(
        "admin/users/<int:profile_id>/role/",
        UserRoleView.as_view(),
        name="user-role",
    ),
    path(
        "admin/trainings/",
        TrainingListCreateView.as_view(),
        name="training-list",
    ),
    path(
        "admin/trainings/<int:training_id>/",
        TrainingDetailView.as_view(),
        name="training-detail",
    ),
    path(
        "admin/trainings/<int:training_id>/objectives/",
        LearningObjectiveListCreateView.as_view(),
        name="learning-objective-list",
    ),
    path(
        "admin/trainings/<int:training_id>/objectives/<int:objective_id>/",
        LearningObjectiveDetailView.as_view(),
        name="learning-objective-detail",
    ),
    path(
        "admin/trainings/<int:training_id>/units/",
        CourseUnitListCreateView.as_view(),
        name="course-unit-list",
    ),
    path(
        "admin/trainings/<int:training_id>/units/<int:unit_id>/",
        CourseUnitDetailView.as_view(),
        name="course-unit-detail",
    ),
    path(
        "admin/trainings/<int:training_id>/raw-materials/",
        RawMaterialListCreateView.as_view(),
        name="raw-material-list",
    ),
    path(
        "admin/trainings/<int:training_id>/enrichments/generate/",
        TrainingEnrichmentGenerateView.as_view(),
        name="training-enrichment-generate",
    ),
    path(
        "admin/trainings/<int:training_id>/structure/generate/",
        TrainingStructureGenerateView.as_view(),
        name="training-structure-generate",
    ),
    path(
        "admin/trainings/<int:training_id>/structure/publish/",
        TrainingStructurePublishView.as_view(),
        name="training-structure-publish",
    ),
    path(
        "admin/trainings/<int:training_id>/raw-materials/<int:material_id>/",
        RawMaterialDetailView.as_view(),
        name="raw-material-detail",
    ),
    path(
        "admin/trainings/<int:training_id>/raw-materials/<int:material_id>/download/",
        RawMaterialDownloadView.as_view(),
        name="raw-material-download",
    ),
    path(
        "admin/trainings/<int:training_id>/raw-materials/<int:material_id>/preview-token/",
        RawMaterialPreviewTokenView.as_view(),
        name="raw-material-preview-token",
    ),
    path(
        "raw-material-previews/<str:token>/",
        RawMaterialPreviewView.as_view(),
        name="raw-material-preview",
    ),
    path("learner/trainings/", LearnerTrainingListView.as_view(), name="learner-trainings"),
]
